name: Prepare Dev Track for Pull Request
description: Prepares track for merge back to main/master.
inputs:
  path:
    description: Path to the Instruqt track.
    required: true
  trackid:
    description: ID of Track
    required: true
runs:
  using: composite
  steps:
  - name: Inject track id and prepare for push
    shell: bash
    run: |

      cd ${{ inputs.path }}

      # Remove the dev suffix and title prefix if they exist, also update tags
      sed -i '0,/^slug/{s/-dev//}' track.yml
      sed -i '0,/^title/{s/DEV - //}' track.yml
      sed -i 's/^- dev/- prod/g' track.yml

      # Replace the track ID with the one provided as an input
      # This should be the production track ID!
      sed -i "s/^id: .*/id: ${{ inputs.trackid }}/g" track.yml

      # Remove maintenance tag
      sed -i 's/^maintenance: true/maintenance: false/g' track.yml