##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow will promote a DEV track back to its PROD version
#
##############################################################################
name: prepare-dev-for-pull-request

env:
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  TRACK_DIR: instruqt-tracks
  
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
    inputs:
      slug:
        description: Track Slug
        required: true
        type: string

jobs:
  PrepareTrackForPullRequest:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main'
    permissions: write-all
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Pull latest track
        uses: ./.github/actions/pull-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ inputs.slug }}

      - name: Update file permissions
        run: sudo chmod -R a+rwx ${{ env.TRACK_DIR }}/${{ inputs.slug }}

      - name: Delete Dev Track
        id: delete-dev-track
        uses: ./.github/actions/delete-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ inputs.slug }}

      - name: Prepare dev track code for PR
        uses: ./.github/actions/prepare-dev-for-pr
        with:
          path: ${{ env.TRACK_DIR }}/${{ inputs.slug }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Creating PR for dev ${{ inputs.slug }} track