##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow will convert DEV track code into PROD track code
##############################################################################
name: prepare-dev-for-pull-request

env:
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  TRACK_DIR: instruqt-tracks
  TRACKID: ""
  
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
    inputs:
      slug:
        description: Track Slug
        required: true
        type: string

jobs:
  PrepareTrackForPullRequest:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
    permissions: write-all
    steps:

      # The first two steps are to get the production track ID and save it as an environment variable
      - name: Check out repository code for the default branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Extract the track id from the track.yml file
        id: get_prod_trackid
        run: |
          echo "TRACKID=$(grep -oP '(?<=id: ).*' instruqt-tracks/${{ inputs.slug }}/track.yml)" >> $GITHUB_ENV

      # Then we check out the development branch to do the work
      - name: Check out repository code for the current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # Pulls directly from Instruqt to ensure we have the latest changes
      - name: Pull latest track
        uses: ./.github/actions/pull-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ inputs.slug }}

      - name: Update file permissions
        run: sudo chmod -R a+rwx ${{ env.TRACK_DIR }}/${{ inputs.slug }}

      # Updates track.yml with the production track ID, prepares for PR
      - name: Prepare dev track code for PR
        run: |
          # Change directory to the track directory
          cd ${{ env.TRACK_DIR }}/${{ inputs.slug }}

          # Remove the dev suffix and title prefix if they exist, also update tags
          sed -i '0,/^slug/{s/-dev//}' track.yml
          sed -i '0,/^title/{s/DEV - //}' track.yml
          sed -i 's/^- dev/- prod/g' track.yml
    
          # Replace the track ID with the production track ID
          sed -i "s/^id: .*/id: ${{ env.TRACKID }}/g" track.yml
    
          # Remove maintenance tag
          sed -i 's/^maintenance: true/maintenance: false/g' track.yml

      # Commits prod-ready changes to the dev branch.
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Creating commit on dev ${{ inputs.slug }} track