##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow file and its actions will run a validate/push/test cycle on
# on a directory full of instruqt tracks. All the tracks in the directory must
# belong to the same Instruqt team.
#
##############################################################################
name: validate-push-test-dev-tracks

env:
  # Set these values to match your environment. Your token should be 
  # stored as a Github secret in your tracks repo. 
  TRACK_DIR: instruqt-tracks
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:

jobs:
  GetTracks:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: Install yq Package
      uses: ./.github/actions/install-yq

    - name: Create Matrix Data
      run: |
        #set -x
        function skip_enabled() {
          if ! [[ -f "$1/track.yml" ]]; then
              echo "Error: $1 is not a valid track directory"
              return 1
          fi
      
          # Run the yq command to check the tags array and return the result
          yq_result=$(yq '.tags | any_c(test("(?i)no-ci|skip-ci|ci-skip"))' "$1/track.yml")
          #echo "$yq_result"
        }

        cd $TRACK_DIR
        for t in $(ls -d *); do
          #echo $t
          if [[ $(skip_enabled $t) == 'true' ]]; then
            echo "Skip CI tag found, skipping $t"
          else
            echo "Adding $t to test matrix"
            CI_TRACKS+=$t
          fi
        done

        #echo $CI_TRACKS

        echo TRACKS="{\\\"tracks\\\":$(echo $CI_TRACKS | jq -R -s -c 'split("\n")[:-1]' | sed 's/"/\\"/g')}" >> $GITHUB_ENV
        echo $GITHUB_ENV
        cat $GITHUB_ENV

    - id: set-matrix
      run: |
        echo "matrix=${{ env.TRACKS }}" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  TestDevTracks:
    runs-on: ubuntu-latest
    if: ${{ needs.GetTracks.outputs.matrix != '[]' && needs.GetTracks.outputs.matrix != '' }}
    needs: GetTracks
    strategy:
      matrix: ${{ fromJson(needs.GetTracks.outputs.matrix) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Install yq Package
        uses: ./.github/actions/install-yq

      - name: Convert to DEV version 
        uses: ./.github/actions/convert-prod-to-dev
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}

      # Remaining steps will skip any tracks that do not have existing DEV variants on Instruqt
      - name: Pull track from instruqt
        id: track-pull
        uses: ./.github/actions/pull-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
        continue-on-error: true
        
      - name: Track Validate
        uses: ./.github/actions/validate-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
        if: steps.track-pull.outcome == 'success'
      
      - name: Track Test
        uses: ./.github/actions/test-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
        if: steps.track-pull.outcome == 'success'
