##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow file and its actions will run a validate/push/test cycle on
# one or more Instruqt tracks directories in your repo. Each job targets a
# separate directory of tracks. All the tracks in each directory must belong
# to the same organization.
#
##############################################################################
name: validate-push-test-prod-tracks

env:
  # Set these values to match your environment. Your token should be 
  # stored as a Github secret in your tracks repo.
  TRACK_DIR: instruqt-tracks
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  GetTrackSlugs:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: Install yq Package
      uses: ./.github/actions/install-yq

    - name: Create Matrix Data
      run: echo "TRACKS=$(ls -d $TRACK_DIR/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

    - id: set-matrix
      run: echo "::set-output name=matrix::${{ env.TRACKS }}"

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  TestProdTracks:
    runs-on: ubuntu-latest
    if: ${{ needs.GetTrackSlugs.outputs.matrix != '[]' && needs.GetTrackSlugs.outputs.matrix != '' }}
    needs: GetTrackSlugs
    strategy:
      matrix: ${{ fromJson(needs.GetTrackSlugs.outputs.matrix) }}
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      # This step checks for the "no-ci" tag on a track
      # If the tag is not present, this step succeeds

      - name: Check CI
        id: check-ci
        uses: ./.github/actions/check-for-no-ci-flag
        with:
          id: ${{ matrix.tracks.id }}
        continue-on-error: true

      - name: Track Validate
        uses: ./.github/actions/validate-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
        if: steps.check-ci.outcome == 'success'
      
      - name: Track Push
        uses: ./.github/actions/push-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
        if: steps.check-ci.outcome == 'success'
      
      - name: Instruqt Track Test
        uses: ./.github/actions/test-track
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
        if: steps.check-ci.outcome == 'success'